// Generated by CoffeeScript 1.9.2

/*
	Teamer Class
 */
var SideStr,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

if (typeof window === "undefined") {
  SideStr = "server";
} else {
  SideStr = "client";
}

console.log("import Teamer \n", "Side is " + SideStr);

exports.TeamerClass = (function() {
  var TeamObject, TeamedParentVariable;

  function TeamerClass() {
    this.team = bind(this.team, this);
  }

  TeamObject = {};

  TeamedParentVariable = null;

  TeamerClass.prototype.team = function(TeamingKeyStr, TeamingValueVariable) {
    console.log(['TeamingKeyStr is ' + TeamingKeyStr, 'TeamingValueVariable is ' + TeamingValueVariable]);
    TeamingValueVariable.TeamedParentVariable = this;
    TeamObject[TeamingKeyStr] = TeamingValueVariable;
    console.log(TeamObject);
    return this;
  };

  return TeamerClass;

})();
