// Generated by CoffeeScript 1.9.2
var FirstTeamer, Teamer;

Teamer = require('./Teamer.js');

FirstTeamer = new Teamer.TeamerClass().team("Children", new Teamer.TeamerClass());

console.log(FirstTeamer);
