// Generated by CoffeeScript 1.9.2

/*
var HelloMessage = React.createClass({displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});

React.render(React.createElement(HelloMessage, {name: "John"}), mountNode);
 */
var a;

a = [[3, "u"], [5, "o"]];

console.log(a);
