// Generated by CoffeeScript 1.9.2
var FirstManager, Manager;

Manager = require('./Manager.js');

FirstManager = new Manager.ManagerClass().manage("Child", new Manager.ManagerClass());

console.log(FirstManager);
