pages:
- [index.md, Home]
- [About/Introduction.md, About, Introduction]
- [About/Manifest.md, About, Manifest]
- [About/StateArt.md, About, State of the art]
- [About/FAQs.md, About, FAQs]
- [GettingStarted/Install.md, GettingStarted, Install ShareYourSystem]
- [GettingStarted/FirstToyObject.md, GettingStarted, Build a first SYS toy object]
- [GettingStarted/UseMeteorApi.md, GettingStarted, Use the Meteror GUI]
- [LibraryReference/Classors.md, Standard Library Reference, Classors]
- [LibraryReference/Classors.md, Standard Library Reference, Functers]
- [LibraryReference/Objects.md, Standard Library Reference, Objects]
- [LibraryReference/Interfacers.md, Standard Library Reference, Interfacers]
- [LibraryReference/Guiders.md, Standard Library Reference, Guiders]
- [LibraryReference/Itemizers.md, Standard Library Reference, Itemizers]
- [LibraryReference/Noders.md, Standard Library Reference, Noders]
- [LibraryReference/Applyiers.md, Standard Library Reference, Applyiers]
- [LibraryReference/Walkers.md, Standard Library Reference, Walkers]
- [LibraryReference/Databasers.md, Standard Library Reference, Databasers]
- [LibraryReference/Storers.md, Standard Library Reference, Storers]
- [LibraryReference/Tutorials.md, Standard Library Reference, Tutorials]
- [LibraryReference/Simulaters.md, Special Library Reference, Simulaters]
- [LibraryReference/Muzikers.md, Special Library Reference, Muzikers]
site_name: ShareYourSystem
theme: readthedocs
