site_name: ShareYourSystem
theme: readthedocs
pages:
- [index.md,Home]
- [Introduction.md,Introduction]
- ['About/Manifest.md','About',Manifest]
- ['About/StateArt.md','About',State of the art]
- ['About/FAQs.md','About',FAQs]
- ['GettingStarted/Install.md','GettingStarted',Install ShareYourSystem]
- ['GettingStarted/FirstToyObject.md','GettingStarted',Build a first hierarching Python object]
- ['GettingStarted/UseMeteorApi.md','GettingStarted',Use the Meteror API]

