// Generated by CoffeeScript 1.9.2
var $, Animal, animal, jsdom,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

$ = require('jquery');

jsdom = require("jsdom");

Animal = (function() {
  function Animal() {
    this.sell = bind(this.sell, this);
  }

  Animal.prototype.price = 5;

  Animal.prototype.sell = function() {
    return alert("Give me " + this.price + " shillings!");
  };

  return Animal;

})();

animal = new Animal;
