// Generated by CoffeeScript 1.9.2
var SYS;

if (typeof window === 'undefined') {
  SYS = require("Coffeelogy.js").SYS;
}

SYS.run(function() {
  var Hello;
  console.log(SYS.React);
  return Hello = SYS.createClass({
    render: function() {
      return React.createElement("div", null, "\t\t\t\t\t\tSALUT");
    }
  });
}, "React", "bower_components/react/react.min.js");
