// Generated by CoffeeScript 1.9.2

/*
console.log(
	[
		'lodash from npm is',
		lodash
	]
)
 */

/*
console.log(
	[
		'lodash from bower is',
		lodash
	]
)
 */
console.log("JJJ");


/*
_screenfull = require('screenfull')
console.log _screenfull
domready = require('domready')
 */
